#comment
name: set-pac-path

description: "add pac cli to path so we can use it directly"

runs:
  using: "composite"
  steps:
    - name: set-pac-path
      shell: pwsh
      run: |
        # hack, but necessary until GitHub Actions for Power Platform support all pac commands
        $actionsPath = "${{ runner.temp }}".Replace("_temp","_actions")
        $array = Get-ChildItem $actionsPath -Recurse | Where-Object{$_.Name.EndsWith('pac.exe')}
        
        $pacPath = $array[0].Directory.FullName
        echo "pacPath: $pacPath"

        echo "$pacPath" | Out-File -FilePath $env:PATH -Encoding utf8 -Append        
