#comment
name: 'get pac path'

description: 'get path to use for Power Platform CLI'

inputs:
  tag:
    description: 'which tag folder to use'
    default: v0
    required: false

outputs:
  path:
    description: "location of pac.exe"
    value: ${{ steps.get-pac-path.outputs.path }}

runs:
  using: "composite"
  steps:
    - id: get-pac-path
      shell: pwsh
      run: |
        # hack, but necessary until GitHub Actions for Power Platform support all pac commands
        $actionsPath = "${{ runner.temp }}".Replace("_temp","_actions")
        $array = Get-ChildItem $actionsPath -Recurse | Where-Object{$_.Name.EndsWith('pac.exe')}       
        $pacPath = $array[0].FullName
        echo "::set-output name=path::$pacPath"