#comment
name: 'get pac path'
description: 'get path to use for Power Platform CLI'
inputs:
  tag:
    description: 'which tag folder to use'
    default: v0
    required: false

outputs:
  path:
    description: "location of pac.exe"
    value: ${{ steps.get-pac-path.outputs.path }}
runs:
  using: "composite"
  steps:
    - id: get-pac-path
      shell: pwsh
      run: |
        # hack, but necessary until GitHub Actions for Power Platform support all pac commands
        $env:PATH
        $gitHubTemp = "${{ runner.temp }}"
        $pacPath = $githubTemp.Replace("_temp","_actions") + "/microsoft/powerplatform-actions/${{ inputs.tag }}\dist\pac\tools/dist/pac_linux/tools"
        echo "::set-output name=path::$pacPath"