name: delete-and-import-unmanaged

on:
  workflow_dispatch:
    inputs:
      x:
        default: 'Hello World2'
  workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:      
      - shell: pwsh
        run: |
          echo "init"