name: delete-and-import-unmanaged

on:
  workflow_dispatch:
    inputs:
      x:
        default: 'workflow_dispatch'
        
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:      
      - shell: pwsh
        run: |
          echo "${{ github.event.inputs.x }}"