name: temp-test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: pwsh
        run: |          
          cd .github/workflows
          Get-ChildItem