name: test-trigger-txt
on:
  pull_request:
    branches:
      - main
      - 'pr**'
    paths:
      - 'src/*/build-deploy-trigger.txt'        
  push:
    branches:      
      - main
      - 'pr**'
    paths:
      - 'src/*/build-deploy-trigger.txt'
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.6

      - name: List all modified files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            echo "$file was modified"
          done