name: test-enable-flows
on:
  push:
    branches:
      - dkdt-140
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2  
      - name: turn-on-flows-impersonation
        id: turn-on-flows-impersonation
        uses: ./.github/actions/turn-on-flows-impersonation
        with:
          environment_url: https://marcsc-alm-demo-dev2.crm.dynamics.com
          solution_name: pvaalm
          tenant_id: ${{ secrets.TENANT_ID }}
          app_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          secrets: ${{ toJSON(secrets) }}
