name: whoami

on:
  workflow_dispatch:

jobs:
  whoami:
    runs-on: ubuntu-latest

    steps:      
      # comment
      - name: call whoami-action
        uses: microsoft/powerplatform-actions/who-am-i@0.4.3
        with:
          environment-url: ${{ secrets.UAT_ENV }}          
          tenant-id: ${{ secrets.TENANT_ID }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}